[package]
name = "christmas"
version = "0.1.0"
authors = ["Daniel Garcia-Briseno <daniel.garcia.briseno@appsolutelywonderful.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
